domain: fedora.test
dns_server_ip: 192.168.180.10
subnet: 192.168.180.0 
netmask: 255.255.255.0
min_address: 192.168.180.30
max_address: 192.168.180.253
brodcast: 192.168.180.254
gateway: 192.168.180.1
filename: pxelinux.0
cluster: ocp4
bootstrap_hostname: bootstrap
master01_hostname: master01
master02_hostname: master02
master03_hostname: master03

bootstrap_ip: 192.168.180.19
master01_ip: 192.168.180.20
master02_ip: 192.168.180.21
master03_ip: 192.168.180.22

bootstrap_mac: "52:54:00:00:32:09"
master01_mac: "52:54:00:00:32:1A"
master02_mac: "52:54:00:00:32:1B"
master03_mac: "52:54:00:00:32:1C"
