bootstrap_hostname: bootstrap
master01_hostname: master01
master02_hostname: master02
master03_hostname: master03


bootstrap_ip: 192.168.140.19
master01_ip: 192.168.140.20
master02_ip: 192.168.140.21
master03_ip: 192.168.140.22


k8s_api_port: 6443
machine_config_port: 22623
ingress_insecure_port: 80
ingress_secure_port: 443
stats_port: 32700

auth: admin:RedH@t322
balance: roundrobin
mode: tcp

ports:
  - 80
  - 443
  - 6443
  - 22623
  - 32700